#:schema node_modules/wrangler/config-schema.json
name = "vpn-clash-v2rayn"
main = "src/worker.jsx"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "9811b5f690f9435a8b528d8611fef838" }
]

[assets]
directory = "./public"
